# =======================
# TARGETS
# =======================

NAME        = push_swap
BONUS_NAME  = checker

# =======================
# COMPILER & FLAGS
# =======================

CC      = cc
CFLAGS  = -Wall -Wextra -Werror

# =======================
# LIBFT
# =======================

LIBFT_DIR = libft
LIBFT     = $(LIBFT_DIR)/libft.a

# =======================
# SOURCES
# =======================

SRCS =  main.c \
        parser.c \
        flags.c \
        index.c \
        disorder.c \
        strategy.c \
        simple_sort.c \
        medium_sort.c \
        complex_sort.c \
        stack_mngr.c \
        frees.c \
        ft_safe_atoi.c \
        print_bench.c \
        pushing.c \
        swapping.c \
        rotating.c \
        rrotating.c

OBJS = $(SRCS:.c=.o)

# =======================
# BONUS
# =======================

BONUS_SRC = checker.c
BONUS_OBJ = $(BONUS_SRC:.c=.o)

# =======================
# RULES
# =======================

all: $(NAME)

$(LIBFT):
    $(MAKE) -C $(LIBFT_DIR)

$(NAME): $(LIBFT) $(OBJS)
    $(CC) $(CFLAGS) $(OBJS) $(LIBFT) -o $(NAME)

bonus: $(LIBFT) $(OBJS) $(BONUS_OBJ)
    $(CC) $(CFLAGS) $(OBJS) $(BONUS_OBJ) $(LIBFT) -o $(BONUS_NAME)

clean:
    rm -f $(OBJS) $(BONUS_OBJ)
    $(MAKE) -C $(LIBFT_DIR) clean

fclean: clean
    rm -f $(NAME) $(BONUS_NAME)
    $(MAKE) -C $(LIBFT_DIR) fclean

re: fclean all

.PHONY: all clean fclean re bonus
