#!/usr/bin/env python3
# *************************************************************************** #
#                                                                             #
#                                                        :::      ::::::::    #
#    battle.py                                         :+:      :+:    :+:    #
#                                                    +:+ +:+         +:+      #
#    By: rodrigoa <rodrigoa@student.42madrid.com>  +#+  +:+       +#+         #
#                                                +#+#+#+#+#+   +#+            #
#    Created: 2026/08/29 16:32:18 by rodrigoa         #+#    #+#              #
#    Updated: 2026/08/29 16:32:18 by rodrigoa        ###   ########.fr        #
#                                                                             #
# *************************************************************************** #
from ex0 import FlameFactory, AquaFactory, CreatureFactory


def test_factory(factory: CreatureFactory) -> None:
    """
    Verifies that a given factory can successfully instantiate
    both base and evolved creature forms, and tests their methods.
    """
    try:
        print("Testing factory")
        base = factory.create_base()
        print(base.describe())
        print(base.attack())

        evolved = factory.create_evolved()
        print(evolved.describe())
        print(evolved.attack())
    except Exception as e:
        print(f"Factory test failed: {e}")


def test_battle(
    factory_one: CreatureFactory, factory_two: CreatureFactory
) -> None:
    """
    Simulates a combat sequence between the base creatures
    generated by two distinct factories.
    """
    try:
        print("Testing battle")
        contender_one = factory_one.create_base()
        contender_two = factory_two.create_base()

        print(contender_one.describe())
        print("vs.")
        print(contender_two.describe())
        print("fight!")

        print(contender_one.attack())
        print(contender_two.attack())
    except Exception as e:
        print(f"Battle simulation failed: {e}")


if __name__ == "__main__":
    flame_factory = FlameFactory()
    aqua_factory = AquaFactory()

    test_factory(flame_factory)
    test_factory(aqua_factory)

    test_battle(flame_factory, aqua_factory)
