#!/usr/bin/env python3
# *************************************************************************** #
#                                                                             #
#                                                        :::      ::::::::    #
#    ft_data_stream.py                                 :+:      :+:    :+:    #
#                                                    +:+ +:+         +:+      #
#    By: rodrigoa <rodrigoa@student.42madrid.com>  +#+  +:+       +#+         #
#                                                +#+#+#+#+#+   +#+            #
#    Created: 2026/07/17 15:00:00 by rodrigoa         #+#    #+#              #
#    Updated: 2026/07/17 15:00:00 by rodrigoa        ###   ########.fr        #
#                                                                             #
# *************************************************************************** #

import random
from typing import Generator


def gen_event() -> Generator[tuple[str, str], None, None]:
    """An endless generator yielding random player events."""
    players = ["alice", "bob", "charlie", "dylan"]
    actions = ["run", "eat", "sleep", "grab", "move", "climb", "swim", "use", "release"]
    
    # The while True loop makes this stream infinite
    while True:
        # yield pauses the function and sends the data back to the caller
        yield (random.choice(players), random.choice(actions))


def consume_event(
        event_list: list[tuple[str, str]]
) -> Generator[tuple[str, str], None, None]:
    """A generator that randomly consumes and yields items until empty."""
    while len(event_list) > 0:
        # Pick a random index from the remaining items
        idx = random.randrange(len(event_list))
        # pop() removes the item from the list and we immediately yield it
        yield event_list.pop(idx)


def ft_data_stream() -> None:
    """Demonstrates generator streams and consumption."""
    print("=== Game Data Stream Processor ===")
    
    # Initialize the infinite stream
    stream = gen_event()
    
    # 1. Loop a thousand times and display events using next()
    for i in range(1000):
        event = next(stream)
        print(f"Event {i}: Player {event[0]} did action {event[1]}")
        
    # 2. Create a list of 10 tuples generated by gen_event()
    event_list: list[tuple[str, str]] = []
    for _ in range(10):
        event_list.append(next(stream))
        
    print(f"\nBuilt list of 10 events: {event_list}\n")
    
    # 3. Consume the list using the consume_event generator in a for loop
    for event in consume_event(event_list):
        print(f"Got event from list: {event}")
        print(f"Remains in list: {event_list}")


if __name__ == "__main__":
    ft_data_stream()